# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui',
# licensing of 'gui.ui' applies.
#
# Created: Wed Nov 21 14:59:58 2018
#      by: pyside2-uic  running on PySide2 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 498)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hboxlayout = QtWidgets.QHBoxLayout()
        self.hboxlayout.setObjectName("hboxlayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelFace = QtWidgets.QLabel(self.centralwidget)
        self.labelFace.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelFace.setText("")
        self.labelFace.setScaledContents(True)
        self.labelFace.setObjectName("labelFace")
        self.verticalLayout.addWidget(self.labelFace)
        self.labelN = QtWidgets.QLabel(self.centralwidget)
        self.labelN.setObjectName("labelN")
        self.verticalLayout.addWidget(self.labelN)
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(20)
        self.labelName.setFont(font)
        self.labelName.setStyleSheet("")
        self.labelName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelName.setObjectName("labelName")
        self.verticalLayout.addWidget(self.labelName)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.labelE = QtWidgets.QLabel(self.centralwidget)
        self.labelE.setObjectName("labelE")
        self.verticalLayout.addWidget(self.labelE)
        self.labelEyes = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.labelEyes.setFont(font)
        self.labelEyes.setStyleSheet("")
        self.labelEyes.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelEyes.setObjectName("labelEyes")
        self.verticalLayout.addWidget(self.labelEyes)
        self.labelM = QtWidgets.QLabel(self.centralwidget)
        self.labelM.setObjectName("labelM")
        self.verticalLayout.addWidget(self.labelM)
        self.labelMouth = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(14)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.labelMouth.setFont(font)
        self.labelMouth.setStyleSheet("")
        self.labelMouth.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelMouth.setObjectName("labelMouth")
        self.verticalLayout.addWidget(self.labelMouth)
        self.labelS = QtWidgets.QLabel(self.centralwidget)
        self.labelS.setObjectName("labelS")
        self.verticalLayout.addWidget(self.labelS)
        self.labelState = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.labelState.setFont(font)
        self.labelState.setStyleSheet("")
        self.labelState.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.labelState.setObjectName("labelState")
        self.verticalLayout.addWidget(self.labelState)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(4, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 1)
        self.verticalLayout.setStretch(7, 1)
        self.verticalLayout.setStretch(8, 1)
        self.verticalLayout.setStretch(9, 1)
        self.hboxlayout.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.hboxlayout.addItem(spacerItem1)
        self.labelFrame = QtWidgets.QLabel(self.centralwidget)
        self.labelFrame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.labelFrame.setText("")
        self.labelFrame.setTextFormat(QtCore.Qt.AutoText)
        self.labelFrame.setScaledContents(True)
        self.labelFrame.setObjectName("labelFrame")
        self.hboxlayout.addWidget(self.labelFrame)
        self.hboxlayout.setStretch(0, 8)
        self.hboxlayout.setStretch(1, 1)
        self.hboxlayout.setStretch(2, 25)
        self.horizontalLayout.addLayout(self.hboxlayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 23))
        self.menubar.setObjectName("menubar")
        self.menuSetting = QtWidgets.QMenu(self.menubar)
        self.menuSetting.setObjectName("menuSetting")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        self.menu_I = QtWidgets.QMenu(self.menubar)
        self.menu_I.setObjectName("menu_I")
        MainWindow.setMenuBar(self.menubar)
        self.actionVoice = QtWidgets.QAction(MainWindow)
        self.actionVoice.setCheckable(True)
        self.actionVoice.setChecked(True)
        self.actionVoice.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionVoice.setShortcutVisibleInContextMenu(False)
        self.actionVoice.setObjectName("actionVoice")
        self.actionLine = QtWidgets.QAction(MainWindow)
        self.actionLine.setCheckable(True)
        self.actionLine.setObjectName("actionLine")
        self.actionVer = QtWidgets.QAction(MainWindow)
        self.actionVer.setObjectName("actionVer")
        self.actionUpdate = QtWidgets.QAction(MainWindow)
        self.actionUpdate.setObjectName("actionUpdate")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionst = QtWidgets.QAction(MainWindow)
        self.actionst.setObjectName("actionst")
        self.actionFlipH = QtWidgets.QAction(MainWindow)
        self.actionFlipH.setCheckable(True)
        self.actionFlipH.setObjectName("actionFlipH")
        self.actionFlipV = QtWidgets.QAction(MainWindow)
        self.actionFlipV.setCheckable(True)
        self.actionFlipV.setObjectName("actionFlipV")
        self.menuSetting.addAction(self.actionVoice)
        self.menuSetting.addAction(self.actionLine)
        self.menuSetting.addSeparator()
        self.menuSetting.addAction(self.actionUpdate)
        self.menuAbout.addAction(self.actionVer)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionst)
        self.menuAbout.addAction(self.actionExit)
        self.menu_I.addAction(self.actionFlipH)
        self.menu_I.addAction(self.actionFlipV)
        self.menubar.addAction(self.menu_I.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "疲劳驾驶监测预警报系统", None, -1))
        self.labelN.setText(QtWidgets.QApplication.translate("MainWindow", "驾驶员：", None, -1))
        self.labelName.setText(QtWidgets.QApplication.translate("MainWindow", "unknown", None, -1))
        self.labelE.setText(QtWidgets.QApplication.translate("MainWindow", "眼睛：", None, -1))
        self.labelEyes.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.labelM.setText(QtWidgets.QApplication.translate("MainWindow", "嘴巴：", None, -1))
        self.labelMouth.setText(QtWidgets.QApplication.translate("MainWindow", "0", None, -1))
        self.labelS.setText(QtWidgets.QApplication.translate("MainWindow", "状态：", None, -1))
        self.labelState.setText(QtWidgets.QApplication.translate("MainWindow", "正常", None, -1))
        self.menuSetting.setTitle(QtWidgets.QApplication.translate("MainWindow", "设置(&S)", None, -1))
        self.menuAbout.setTitle(QtWidgets.QApplication.translate("MainWindow", "关于(A)", None, -1))
        self.menu_I.setTitle(QtWidgets.QApplication.translate("MainWindow", "图像(&I)", None, -1))
        self.actionVoice.setText(QtWidgets.QApplication.translate("MainWindow", "声音", None, -1))
        self.actionLine.setText(QtWidgets.QApplication.translate("MainWindow", "轮廓", None, -1))
        self.actionVer.setText(QtWidgets.QApplication.translate("MainWindow", "版本信息", None, -1))
        self.actionUpdate.setText(QtWidgets.QApplication.translate("MainWindow", "更新数据", None, -1))
        self.actionExit.setText(QtWidgets.QApplication.translate("MainWindow", "退出", None, -1))
        self.actionst.setText(QtWidgets.QApplication.translate("MainWindow", "暂停", None, -1))
        self.actionFlipH.setText(QtWidgets.QApplication.translate("MainWindow", "水平翻转", None, -1))
        self.actionFlipV.setText(QtWidgets.QApplication.translate("MainWindow", "垂直翻转", None, -1))

